---
title: "Data Visualization Report"
subtitle: "`r study_id`"
author: "Coastal Carbon Research Coordination Network"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    theme: spacelab
    highlight: tango
---

```{r setup, include=FALSE}
# this sets the working directory to start where the R project is located
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

# no warnings or messages
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

# load libraries
library(leaflet)
library(DT)
```

# Core-level

## Core Locations
```{r}
# plot core locations
leaflet(cores, width = "100%") %>% 
  addTiles() %>% 
  addCircleMarkers(lng = ~longitude, lat = ~latitude, radius = 3, label = ~core_id)
```

# Depthseries

## Bulk Density, Carbon, and OM
``` {r bd and om}

ds_cols <- names(depthseries)

# OM ~ DBD
if("fraction_organic_matter" %in% ds_cols & "dry_bulk_density" %in% ds_cols){
  depthseries %>% drop_na(dry_bulk_density, fraction_organic_matter) %>%
    ggplot(aes(x=fraction_organic_matter, dry_bulk_density, color = site_id)) +
    geom_point(alpha = 0.6) +
    xlab("Organic Matter (fraction)") +
    ylab(expression(paste("Dry Bulk Density (g cm"^"-3",")", sep=""))) +
    theme_bw() +
    ggtitle("OM ~ DBD")
}

```

```{r bd and c}
# C ~ DBD
if("fraction_carbon" %in% ds_cols & "dry_bulk_density" %in% ds_cols){
  depthseries %>% drop_na(dry_bulk_density, fraction_carbon) %>% 
    ggplot(aes(x=fraction_carbon, dry_bulk_density, color = site_id)) +
    geom_point(alpha = 0.6) +
    xlab("Carbon (fraction)") +
    ylab(expression(paste("Dry Bulk Density (g cm"^"-3",")", sep=""))) +
    theme_bw() +
    ggtitle("C ~ DBD")
}
```

``` {r om and oc}
# visual inspection to determine whether there are modeled values
if("fraction_carbon" %in% ds_cols & "fraction_organic_matter" %in% ds_cols){
  depthseries %>% drop_na(fraction_organic_matter, fraction_carbon) %>% 
    ggplot(aes(x = fraction_organic_matter, y = fraction_carbon, color=site_id)) +
    geom_point(alpha = 0.6) + 
    xlab("Organic Matter (fraction)") +
    ylab("Organic Carbon (fraction)") +
    theme_bw() +
    ggtitle("Carbon ~ Organic Matter")
}
```

## Depth Profiles

``` {r om depth profile, fig.height=12, fig.width=12}
# Burden dataset problematic b/c there's only one 0-30 increment per core
if("fraction_organic_matter" %in% ds_cols){
  depthseries %>% drop_na(fraction_organic_matter) %>% 
    ggplot(aes(x=depth_min, y=fraction_organic_matter)) +
    geom_point(size = 2, pch=21, fill="white") +
    geom_line() +
    facet_wrap(~core_id, dir = "v") +
    scale_x_reverse() +
    ylab("Organic Matter (fraction)") +
    xlab("Max Depth (cm)") +
    coord_flip() +
    theme_bw(base_size = 15) +
    ggtitle("OM (LOI) Depth Profiles")
}
```

``` {r c depth profile}
if("fraction_carbon" %in% ds_cols){
  plot_c_profiles <- depthseries %>% drop_na(fraction_carbon) %>% 
    ggplot(aes(x=depth_min, y=fraction_carbon)) + 
    geom_line() +
    geom_point(size = 2, pch=21, fill="white") +
    facet_wrap(~core_id, dir = "v") +
    scale_x_reverse() +
    ylab("Carbon (fraction)") +
    xlab("Max Depth (cm)") +
    coord_flip() +
    theme_bw(base_size = 15) +
    ggtitle("C Depth Profiles")
}
```

<style>
  .superbigimage{
      overflow-y:scroll;
      white-space: nowrap;
  }

  .superbigimage img{
     max-height: none;
  }
</style>

This produces the plot with a special css class
<div class="superbigimage">
```{r plot_it, fig.width=12}
plot_c_profiles
```
</div>

``` {r bd depth profiles, fig.height=12, fig.width=12}
# there should be DBD, shouldn't need if statement
depthseries %>% drop_na(dry_bulk_density) %>% 
  ggplot(aes(x=depth_min, y=dry_bulk_density)) +
  geom_line() +
  geom_point(size = 2, pch=21, fill="white") +
  facet_wrap(~core_id) +
  ylab(expression(paste("Dry Bulk Density (g cm"^"-3",")", sep=""))) +
  xlab("Max Depth (cm)") +
  scale_x_reverse() +
  coord_flip() +
  theme_bw(base_size = 15) +
  ggtitle("Bulk Density Profiles")
```

``` {r 210Pb depth profiles, fig.height=12, fig.width=12}

if(c("ra226_activity", "total_pb210_activity", "excess_pb210_activity") %in% ds_cols){ # make this better
  # total_pb210_activity_se may need to be calculated:
# pbsubset <- depthseries %>% 
#   drop_na(excess_pb210_activity, ra226_activity) %>% 
#   mutate(total_pb210_activity_se = excess_pb210_activity + ra226_activity)
# though it may already exist for some datasets

pbdata_se <- depthseries %>%
  # mutate(ra226_activity_se = NA,
  #        total_pb210_activity_se = NA) %>% 
  select(core_id, depth_min,
         ra226_activity_se, total_pb210_activity_se, excess_pb210_activity_se) %>%
  rename(ra226_activity = ra226_activity_se, 
         total_210Pb_activity = total_pb210_activity_se,
         excess_pb210_activity = excess_pb210_activity_se) %>%
  gather(key="element", value="radioactivity_se", -core_id, -depth_min) %>% 
  drop_na(radioactivity_se)

pbdata <- depthseries %>%
  select(core_id, depth_min, total_pb210_activity,
         ra226_activity, excess_pb210_activity) %>%
  gather(key="element", value="radioactivity", -core_id, -depth_min) %>% 
  drop_na(radioactivity) %>% 
  left_join(pbdata_se)

ggplot(pbdata, aes(x = depth_min, y = radioactivity, color = element)) +
  geom_line() +
  geom_point(size = 2, pch=21, fill="white") +
  geom_segment(aes(x = depth_min, y = radioactivity - radioactivity_se,
                   xend = depth_min, yend = radioactivity + radioactivity_se)) +
  facet_wrap(~core_id) +
  xlab("Max Depth (cm)") + 
  ylab(expression(paste("Radioactivity (dpm g"^"-1",")",sep=""))) +
  scale_x_reverse() +
  coord_flip() +
  theme_bw(base_size = 15) +
  theme(legend.position="bottom") +
  ggtitle("Pb-210 Depth Profiles")
}
```

``` {r age depth models, fig.height=12, fig.width=12}
if("age" %in% ds_cols){
  ggplot(depthseries %>% drop_na(age), aes(x = depth_min, y = age)) +
  geom_line() +
  facet_wrap(~core_id) +
  scale_x_reverse() +
  ylab("Age") +
  xlab("Max Depth (cm)") +
  coord_flip() + theme_bw(base_size = 15) +
  ggtitle("Age Depth Models") # plot error if present
}
```

``` {r cs profile, fig.height=12, fig.width=12}
if("cs137_activity" %in% ds_cols){
  depthseries %>% drop_na(cs137_activity) %>% 
    ggplot(aes(x = depth_min, y = cs137_activity)) +
    geom_line() +
    geom_point(size = 2, pch=21, fill="white") +
    facet_wrap(~core_id) +
    scale_x_reverse() +
    ylab("Cs-137 Activity") +
    xlab("Max Depth (cm)") +
    coord_flip() + theme_bw(base_size = 15) +
    ggtitle("Cesium-137 Depth Profiles") # plot error if present
}
```